name: Run DPC Pipeline

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 01:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-dpc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout code

      - name: Setup R
        uses: r-lib/actions/setup-r@v2  # Set up R environment

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("httr","jsonlite","terra","lubridate","googledrive","base64enc"))'

      - name: Run download script
        run: Rscript DOWNLOAD_DPC.R

      - name: Run aggregation script
        run: Rscript AGGREGA_DAILY_DPC.R

      - name: Upload aggregated files to Google Drive
        env:
          GDRIVE_PAT: ${{ secrets.GDRIVE_PAT }}  # Use the secret here
        run: Rscript upload_to_drive.R
